name: SimpleLunchboxes
version: '${project.version}'
main: simplexity.simplelunchboxes.SimpleLunchboxes
api-version: '1.20.5'
commands:
  giveqolfood:
    description: "Testing command for Simple QoL Food"